fp-bindgen-support/Cargo.toml
fp-bindgen/Cargo.toml

The docs.rs documentation for `fp-bindgen` is currently built without
all features enabled. This can be confusing, as types that are mentioned
in the README are not present in the API reference. This pull request
should take care of that, by telling docs.rs to pass `--all-features` to
`cargo doc`.
I haven't tested this, but I think it should work. The `docs.rs`
documentation on the topic seems straight-forward enough:
https://docs.rs/about/metadata
Close #120

Build docs.rs documentation with `--all-features`

---

examples/example-deno-runtime/tests.ts
examples/example-plugin/src/lib.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_types.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_types.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_types.ts
examples/example-protocol/src/types/http.rs
examples/example-rust-runtime/src/spec/mod.rs
examples/example-rust-runtime/src/test.rs
fp-bindgen-support/src/http/mod.rs
fp-bindgen/src/serializable/http.rs

closes #102. Converts existing `HashMap<string, string>` types to `http::HeaderMap`.

HTTP HeaderMaps (de)serialize support #102

---

CHANGELOG.md
examples/example-deno-runtime/tests.ts
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_types.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_types.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/assets/ts_runtime_test/expected_types.ts
examples/example-protocol/src/main.rs
examples/example-protocol/src/types/generics.rs
examples/example-rust-runtime/src/spec/mod.rs
fp-bindgen/src/generators/mod.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/generators/ts_runtime/mod.rs
fp-bindgen/src/serializable/mod.rs
fp-bindgen/src/types/enums.rs
fp-bindgen/src/types/mod.rs
fp-bindgen/src/types/structs.rs
fp-bindgen/src/types/type_ident.rs
macros/src/serializable.rs

This solves the issue mentioned in #88 where trait bounds were incorrectly suffixed with `: Serializable` even if that bound was already present. Additionally, it allows the use of other bounds whereas previously any additional bounds would cause `collect_types` to be invoked incorrectly.

Properly deal with generic bounds in codegen

---

CHANGELOG.md
examples/example-deno-runtime/tests.ts
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
examples/example-rust-runtime/src/spec/mod.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

If custom types were used in generic positions (such as `Result<ByteBuf, ...>`), the identifier wasn't using the proper formatting, which could result in their Rust formatting not being specified.
Also removed unnecessary parentheses in the Wasmer runtime bindings for functions that only have a single argument. This prevents a bunch of compiler warnings.

Fix custom types in generic positions

---

CHANGELOG.md
examples/example-protocol/src/assets/rust_plugin_test/expected_export.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
fp-bindgen/src/functions.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs
fp-bindgen/src/types/mod.rs
fp-bindgen/src/types/type_ident.rs

Note this does revert to a string-based approach for generating the Rust wasmer runtime, but it saves a lot of code and duplication.

Fix custom types in generic positions in export function signatures

---

CHANGELOG.md
examples/example-deno-runtime/tests.ts
examples/example-plugin/src/lib.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_export.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
examples/example-rust-runtime/src/spec/mod.rs
examples/example-rust-runtime/src/test.rs
fp-bindgen-support/src/host/errors.rs
fp-bindgen/src/functions.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs
fp-bindgen/src/generators/ts_runtime/mod.rs
fp-bindgen/src/primitives.rs
fp-bindgen/src/serializable/mod.rs
fp-bindgen/src/types/enums.rs
fp-bindgen/src/types/mod.rs
fp-bindgen/src/types/structs.rs
fp-bindgen/src/types/type_ident.rs
macros/src/lib.rs
macros/src/primitives.rs
macros/src/serializable.rs
macros/src/typing.rs
macros/src/utils.rs

Closes #94.
This change introduces support for primitive arrays, using TypedArrays on the JS side.

Support for primitive arrays

---

CHANGELOG.md
README.md
examples/example-deno-runtime/tests.ts
examples/example-plugin/Cargo.toml
examples/example-plugin/src/lib.rs
examples/example-protocol/Cargo.toml
examples/example-protocol/src/assets/rust_plugin_test/expected_Cargo.toml
examples/example-protocol/src/assets/rust_plugin_test/expected_export.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
examples/example-rust-runtime/Cargo.toml
examples/example-rust-runtime/src/spec/mod.rs
examples/example-rust-runtime/src/test.rs
fp-bindgen/Cargo.toml
fp-bindgen/src/generators/ts_runtime/mod.rs
fp-bindgen/src/serializable/bytes.rs
fp-bindgen/src/serializable/mod.rs
fp-bindgen/src/types/type_ident.rs

Similar to how we support `serde_bytes`.
Also fixes an issue with how we free memory when nested `Uint8Array` objects are encoded inside a MessagePack payload.

Implement compatibility with `bytes` crate

---

examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

The Wasmer `Module` that the `Runtime` wraps implements `Clone` so the `Runtime` should too. This allows us to compile the wasm code once and clone the `Runtime` to handle multiple requests.

Derive Clone for Runtime

---

.github/workflows/test.yml
examples/example-plugin/rust-toolchain.toml

c36797991dd35b0d60aa4c16866d60d9d280febe introduced the need for a nightly compiler because certain crates needed to be compiled for multiple targets. Rust 1.64.0 now supports this in stable as well, so we don't need nightly anymore.

Now that Rust 1.64.0 is out we don't need nightly anymore

---

fp-bindgen/src/serializable/http.rs
fp-bindgen/src/serializable/rmpv.rs
fp-bindgen/src/serializable/time.rs
fp-bindgen/src/types/cargo_dependency.rs

Adds support for [workspace dependences](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace), which were added in Rust 1.64.

Support workspace dependencies

---

xtask/src/test.rs

The wasmer runtime path was not updated, causing `xtask test` to fail.

Fix xtask wasmer path

---

examples/example-protocol/Cargo.toml
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
examples/example-rust-wasmer-runtime/Cargo.toml
examples/example-rust-wasmer-runtime/src/main.rs
examples/example-rust-wasmer-runtime/src/test.rs
fp-bindgen-support/Cargo.toml
fp-bindgen-support/src/common/abi.rs
fp-bindgen-support/src/common/async.rs
fp-bindgen-support/src/host/async/future.rs
fp-bindgen-support/src/host/async/mod.rs
fp-bindgen-support/src/host/io.rs
fp-bindgen-support/src/host/mem.rs
fp-bindgen-support/src/host/runtime.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs
fp-bindgen/src/generators/rust_wasmer_wasi_runtime/mod.rs
xtask/src/test.rs

Based on the recent work in the `guest-tracing` and `reuse-instance` branches.
Replaces https://github.com/fiberplane/fp-bindgen/pull/153.
This was branched off of https://github.com/fiberplane/fp-bindgen/pull/156.
I might still try to move the async runtime to a lazily initialized cell instead of creating one per async request.

Wasmer 3 migration

---

examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
examples/example-rust-wasmer-runtime/Cargo.toml
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

Opening this to tackle this issue: https://github.com/fiberplane/fp-bindgen/issues/161
- Just updated the import of `Singlepass` from wasmer.

Fix 'Singlepass' import for Runtime bindings. 

---

CHANGELOG.md
README.md
examples/README.md
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_types.rs
examples/example-protocol/src/types/time.rs
examples/redux-example/src/lib.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs
fp-bindgen/src/generators/rust_wasmer_wasi_runtime/mod.rs
fp-bindgen/src/lib.rs
fp-bindgen/src/types/enums.rs
fp-bindgen/src/types/structs.rs

Cleans up that annotation and simplifies the code related to it.

Simplify the rust-module annotation so it works the same for all generators that choose to support it

---

xtask/src/clean.rs
xtask/src/main.rs

I added this since I had some issues after updating Rust, and running `cargo clean` in the root folder doesn't clean up enough.

Add a 'clean' xtask that cleans all target folders and generated bindings

---

examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

The Tokio runtime that gets created ad-hoc to deal with awaiting async results did not get IO enabled. This causes any WASM code that is trying to wait for something like an HTTP request to blow up.

Call `enable_all` on Tokio runtime

---

examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
examples/example-rust-wasmer-runtime/Cargo.toml
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

Imports were apparently using direct crate references, instead of using the names re-exported from the main `wasmer` crate.
We don't want this, since this forces users to add extra crates to their project.

Fix imports in generated bindings

---

fp-bindgen/src/types/cargo_dependency.rs

Adds two helper methods for convenience now that `CargoDependency` is non-exhaustive.

Add `from_workspace()` builder methods

---

CHANGELOG.md
fp-bindgen/src/types/cargo_dependency.rs

Howdy!
This change allows use of the `git` and `branch` fields on `CargoDependency`. As far as I can tell, these are unusable w/o a helper because `CargoDependency` is _non exhaustive_ and _immutable_. 
I'm not sure if it's worth having four methods here. Perhaps `with_git_and_branch` and `with_git_and_branch_and_features` is sufficient.

cargo_dependency: add git helpers

---

CHANGELOG.md
Cargo.toml
examples/example-protocol/src/assets/rust_plugin_test/expected_Cargo.toml
examples/example-protocol/src/assets/rust_plugin_test/expected_Cargo_no_optionals.toml
examples/example-protocol/src/main.rs
fp-bindgen/Cargo.toml
fp-bindgen/src/generators/mod.rs
fp-bindgen/src/generators/rust_plugin/mod.rs
fp-bindgen/src/lib.rs
fp-bindgen/src/prelude.rs

This allows the `description` and `license` fields to be specified in `RustPluginConfig` and passed on to the generated `Cargo.toml`.

Add support for adding 'description' and 'license' fields

---

fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs

The original code actually fails on this line if the guest function doesn't return an result, which is already fishy.
Removing the unwrap solves the problem.

Fix erroneous unwrap in async export function

---

CHANGELOG.md
examples/example-deno-runtime/tests.ts
examples/example-plugin/src/lib.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_export.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
examples/example-rust-wasmer-runtime/src/spec/mod.rs
examples/example-rust-wasmer-runtime/src/test.rs

Adding tests that go back and forth makes the testing more robust, as it tests the interaction of a larger part of the system.
Addresses #180, but there is still more to do, for example generating a warning when an imported function takes `f32`/`f64`, or marking it as deprecated with a link to this issue.

Make primitive tests go back and forth, fix float params in imported functions

---

CHANGELOG.md
examples/example-deno-runtime/tests.ts
examples/example-plugin/src/lib.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_export.rs
examples/example-protocol/src/assets/rust_plugin_test/expected_import.rs
examples/example-protocol/src/assets/rust_wasmer_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer_wasi_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
examples/example-rust-wasmer-runtime/src/main.rs
examples/example-rust-wasmer-runtime/src/spec/mod.rs
examples/example-rust-wasmer-runtime/src/test.rs
fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs
fp-bindgen/src/generators/rust_wasmer_wasi_runtime/mod.rs
fp-bindgen/src/generators/ts_runtime/mod.rs
macros/src/lib.rs
macros/src/typing.rs

The current bindgen code did not exactly expect async functions to return non-complex values. This PR updates both the wasmer runtime generation and the typescript deno runtime generation code to correctly encode async functions that return a primitive value or don't return anything, as well as adds tests in the example projects for it. Fixes [#178](https://github.com/fiberplane/fp-bindgen/issues/178).
Notable commits:
- [Update wasmer runtime generation](https://github.com/kajacx/fp-bindgen/commit/1c02dd4553a4932bac94f296637cf770ad9332db)
- [Update wasmer host generated bindings](https://github.com/kajacx/fp-bindgen/commit/78d37d95c8d5d484e130bc620c674f2c966a7925)
- [Update TS deno runtime generation](https://github.com/kajacx/fp-bindgen/commit/e710e9e0c8c4561454408f3bac4d07ccd832d7f0)
- …

Fix async functions that return a primitive

---

examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
fp-bindgen/src/generators/ts_runtime/mod.rs

`fromFatPtr()` used to convert `BigInt` values to string before parsing them as numbers again, which really shouldn't be necessary. It's probably negligible on the whole, but a low hanging fruit anyway.

Optimize `fromFatPtr()`

---

CHANGELOG.md
examples/example-deno-runtime/loader.ts
examples/example-protocol/src/assets/ts_runtime_test/expected_index.ts
examples/example-protocol/src/main.rs
fp-bindgen/src/generators/mod.rs
fp-bindgen/src/generators/ts_runtime/mod.rs
fp-bindgen/src/lib.rs
fp-bindgen/src/prelude.rs

MDN says the following about `WebAssembly.instantiate()`:
> This method is not the most efficient way of fetching and instantiating wasm modules. If at all possible, you should use the newer [WebAssembly.instantiateStreaming()](https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiateStreaming) method instead, which fetches, compiles, and instantiates a module all in one step, directly from the raw bytecode, so doesn't require conversion to an [ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).
- https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface/instantiate
So as we're preparing to release `fp-bindgen` 3.0, we might as well make `instantiateStreaming()` the new default.

Implement streaming instantiation for TS runtime

---

examples/example-protocol/Cargo.toml

Tiny fix to no longer use an outdated version of `pretty_assertions` which depended on unmaintained crates (`ansi_term`).
Fixes https://github.com/fiberplane/monofiber/issues/90

Bump `pretty_assertions` dependency

---

fp-bindgen/src/functions.rs
fp-bindgen/src/types/type_ident.rs

Looks like newer Clippy versions are more strict about the implementation of `PartialOrd`. If the type also implements `Ord`, `partial_cmp()` must defer to `cmp()` to guarantee consistent behavior.

Fix Clippies about `partial_cmp()`

---

fp-bindgen-support/Cargo.toml
fp-bindgen/Cargo.toml
macros/Cargo.toml

This will make sure the versions are defined currently when included from our `monofiber` setup.

Explicitly specify crate versions

---

examples/example-protocol/src/assets/rust_wasmer2_runtime_test/expected_bindings.rs
examples/example-protocol/src/assets/rust_wasmer2_wasi_runtime_test/expected_bindings.rs
fp-bindgen/src/generators/rust_wasmer2_runtime/mod.rs

This adds an exception to the generated Rust bindings so that they don't trigger a bunch of Clippy warnings.

Fix Clippies

---

fp-bindgen/src/casing.rs

Required for Mari's PR on adding models for Integrations:
https://github.com/fiberplane/fiberplane/pull/142/files#diff-40ccb6419f9490941019eb957d439ce51f0991b242c8c0522f491a646a382102R38

Add support for lowercase in rename casing

---

CHANGELOG.md
fp-bindgen/src/generators/mod.rs
fp-bindgen/src/generators/rust_plugin/mod.rs

This will generate publish=false as an actual toml bool, instead of a string value

Generate value as bool
